### ISSUE TITLE
SSL connection errors trying to connect

### ISSUE THREAD

**Issue by oliof** [Mattalabs/OctoPrint-Mattacloud#13]
This is with OctoPrint 1.5rc1

from the octoprint logs

```
2020-11-11 13:27:42,567 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/pi/oprint/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_mattacloud/webcam.py", line 34, in offer
    player = MediaPlayer("http://127.0.0.1:8080/?action=stream")
NameError: name 'MediaPlayer' is not defined
2020-11-11 13:27:42,635 - octoprint.plugins.mattacloud - ERROR - 500 Server Error: Internal Server Error for url: http://127.0.0.1:8888/offer
2020-11-11 13:27:42,807 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/pi/oprint/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_mattacloud/webcam.py", line 34, in offer
    player = MediaPlayer("http://127.0.0.1:8080/?action=stream")
NameError: name 'MediaPlayer' is not defined
2020-11-11 13:27:42,942 - octoprint.plugins.mattacloud - ERROR - 500 Server Error: Internal Server Error for url: http://127.0.0.1:8888/offer
```

and shortly after

```
2020-11-11 13:33:40,808 - octoprint.plugins.mattacloud - ERROR - Socket send_msg: EOF occurred in violation of protocol (_ssl.c:2341)
2020-11-11 13:33:41,142 - octoprint.plugins.mattacloud - ERROR - Socket send_msg: [Errno 32] Broken pipe
2020-11-11 13:33:41,154 - octoprint.plugins.mattacloud - ERROR - ws_on_error: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2488), URL: https://cloud.mattalabs.com, Token: XXXXXXXXXXXXXXXXXXXXXXX
```

On a reboot, the connection worked, but with the printer off, I cannot see the video stream.

**Comment by dougbrion** [comment]
Sorry it has taken a while to respond to this! To me it looks like a few requirements might still need to be installed for the video stream to work.

In your Python 3 environment if you try this import `from aiortc.contrib.media import MediaPlayer` does it error? It may suggest that additional packages are required (possibly for opencv to work).

**Comment by kgleason** [comment]
Not sure if it matters. I also have issues getting the stream to start when the printer is not running. I've not seen any SSL errors, but when I try your import, I get the following:

Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>>from aiortc.contrib.media import MediaPlayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/oprint/lib/python3.7/site-packages/aiortc/contrib/media.py", line 6, in <module>
    import cv2
  File "/home/pi/oprint/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libImath-2_2.so.23: cannot open shared object file: No such file or directory

**Comment by dougbrion** [comment]
There is a new update of this plugin which _should_ be working out of the box hopefully without additional requirements.
I just installed it alone on a clean version of OctoPi 0.18.0 and it appears to work fine.

@kgleason it might be worth installing the following packages and seeing if it can import `MediaPlayer` then:

```
sudo apt-get install libilmbase-dev libopenexr-dev libgstreamer1.0-dev
```

as a quick check you can just trying importing `MediaPlayer` in a Python shell. Activate your virtualenv, if you are using octoprint it is:

```
`source ~/oprint/bin/activate`
```

Then run `python` and just try the line `from aiortc.contrib.media import MediaPlayer`. See if it still errors after installing the update and the packages above.

**Comment by kgleason** [comment]
I installed the packages you recommended, and I get a similar exception:

```
>>> from aiortc.contrib.media import MediaPlayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/oprint/lib/python3.7/site-packages/aiortc/contrib/media.py", line 6, in <module>
    import cv2
  File "/home/pi/oprint/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

Raspbian is all up to date, and I don't see any available updates in OctoPrint.
I am using Python 3, if it matters at all.

**Comment by kgleason** [comment]
I followed the exceptions, and installed quite a few more packages:

 `sudo apt install libgtk-3-dev liblapack-dev libatlas-base-dev`

And I ended up with this:

```
>>> from aiortc.contrib.media import MediaPlayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MediaPlayer' from 'aiortc.contrib.media' (/home/pi/oprint/lib/python3.7/site-packages/aiortc/contrib/media.py)
```
